void start(){
    int x=850,y=650,i,l=644,t=548,r=800,b=570;
    initwindow(x,y,"TRAFFIC RACING");
    readimagefile("img/front/front.jpg",0,0,x,y);
    delay(120);
    readimagefile("img/front/frontl.jpg",0,0,x,y);
    setcolor(WHITE);
    rectangle(l,t,r,b);
    rectangle(l-1,t-1,r+1,b+1);
    setcolor(getpixel(574,210));
    l=l+1;
    t=t+1;
    b=b-1;
    for(i=0; i<=153; ++i)
    {
        rectangle(l+i,t,l+i+1,b);
        delay(9);
    }
    settextstyle(6,HORIZ_DIR,5);
    outtextxy(252,349,"Loading Complete!");
    delay(180);
    readimagefile("img/front/front26.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front25.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front24.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front23.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front22.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front21.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front20.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front19.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front18.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front17.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front16.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front15.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front14.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front13.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front12.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front11.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front10.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front9.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front8.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front7.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front6.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front5.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front4.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front3.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front2.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front1.jpg",0,0,x,y);
    delay(12);
    readimagefile("img/front/front27.jpg",0,0,x,y);
    delay(100);
    while(1)
    {
        readimagefile("img/front/front.jpg",0,0,x,y);
        delay(400);
        readimagefile("img/front/front27.jpg",0,0,x,y);
        delay(400);
        if(kbhit())
        {
            char ch=getch();
            if (ch==13)
                break;
        }
    }
}
